appName: node-app

replicaCount: 1

image:
  repository: "image-registry.openshift-image-registry.svc:5000/practice-talks/node-app"
  pullPolicy: IfNotPresent
  tag: "latest"

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080
  target: 3000

route:
  host: node-app
  domain: apps.ocp4.example.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}
